Revert "[Security] Bump websocket-extensions from 0.1.3 to 0.1.4 (#1288)" (#1294)
This reverts commit 9d7fe9065774be34a957f25a0c7ae1d878db647b.

The github publishing workflow began failing after this commit with the following error:

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'